In [3]:
import sys
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Input, Convolution1D, Convolution2D
from keras.regularizers import l2, activity_l2

from random import randint
from keras.layers import Merge, LSTM, Dense
# Features: ['Adj_Close', 'Close', 'Date', 'High', 'Low', 'Open', 'Symbol', 'Volume']
from sklearn import preprocessing

testData = np.genfromtxt('testData.txt', dtype = None)


In [4]:
# # Part 1  
# # One single featuere
# X0 = [] # Adj_Close
# X1 = [] #
# X2 = [] #
# X3 = [] #
# X4 = [] # High
# X5 = [] #

# for tuple in testData:
#     X4.append(tuple[4])
# #####(..)start
# X4n2= preprocessing.normalize(X4) #,norm='l2')
# X4n2=X4n2[0]
# #####(..)end
# size = 1000
# window = 25
# X = np.empty([0, window])
# Y = np.zeros(size)
# batchSize = 10

# for i in range(size):
#     start = randint(0, len(testData)-window-1)
#     X = np.concatenate((X, np.asarray(X4n2[start : start + window]).reshape(1, window)), axis = 0)
# ##(..)
#     Y[i] = X4[start + window]  #Y dont want denormalized
# ################################################

# print(X.shape)
# print(Y.shape)
# print X[0]
# print Y[0]

# model = Sequential()
# model.add(Dense(1, input_dim = window))
# keras.optimizers.RMSprop(lr=0.01, rho=0.9, epsilon=1e-08, decay=0.0)
# model.compile(optimizer='rmsprop',loss='mse') # for a mean squared error regression problem
# history = model.fit(X, Y, validation_split=0.33, batch_size=batchSize, nb_epoch=1000, initial_epoch=0)
# print(history)

In [5]:
# plt.axis((0, 20, 0, 50))
# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train', 'test'], loc='upper left')
# plt.show()

In [6]:
# training_loss = model.evaluate(X, Y, batch_size=batchSize, verbose=1)
# print("\nMSE: {}".format(training_loss))

In [7]:
# scope = 20  # should be smaller than len(Y)
# YHat = model.predict(X, batch_size=batchSize, verbose=0)
# YHat = np.ravel(YHat)
# x = np.arange(0, scope)
# plt.figure(figsize=(20,10))
# plt.plot(x, Y[0:scope], 'b', x, YHat[0:scope], 'r')
# plt.show()
# training_loss = model.evaluate(X, Y, batch_size=batchSize, verbose=1)

In [8]:
# Part 2
# Multiple featueres
# X0 = [] # Adj_Close
# X1 = [] #
# X2 = [] #
# X3 = [] #
# X4 = [] # High
# X5 = [] #

# Features: ['Adj_Close', 'Close', 'Date', 'High', 'Low', 'Open', 'Symbol', 'Volume']

# make feature 2 - dates to be number comvertable
for tuple in testData:
    tuple[2] = tuple[2].replace("-", "")
    
# convert feature 6 - stock name to be stock-id (Yahoo == 1)
for tuple in testData:
    tuple[6] = 1

# 7 features so far
data = [[], [], [], [], [], [], [], []]  #add []
for tuple in testData:
    for i in range(len(data)):
            data[i].append(float(tuple[i]))
            #print i

for i in range(len(data)):
    data[i]= preprocessing.normalize(data[i]) #,norm='l2')
    data[i] = data[i][0]
    #print i
#print data[7]#(..)
# Remove redunt features
# Features: ['Adj_Close', 'Close', 'Date', 'High', 'Low', 'Open', 'Symbol', 'Volume']
data = [data[0], data[1], data[3], data[4], data[5],data[7]]
            
# convert data into numpy 2d array
data = np.asarray(data)   

print(data.shape)

# print(X)
print data[0]

(6, 756)
[ 0.03603396  0.03600601  0.03608987  0.03626692  0.03602465  0.03587555
  0.03648125  0.03649056  0.035801    0.03597806  0.03579169  0.03812127
  0.0386431   0.03848468  0.03891333  0.03858719  0.03775786  0.03724535
  0.03745967  0.03733853  0.03692853  0.03822377  0.03876423  0.03862446
  0.038084    0.03816786  0.03821445  0.03830764  0.03838218  0.03862446
  0.0381865   0.03746899  0.03662102  0.03766467  0.0374224   0.03840082
  0.03835423  0.03825173  0.03753421  0.03748762  0.03790695  0.03851264
  0.03871764  0.03893196  0.03901583  0.03921152  0.03964947  0.03968675
  0.03929538  0.03949106  0.03981721  0.03883878  0.03894128  0.03861514
  0.03878287  0.03947243  0.03977061  0.04092608  0.0402738   0.04070245
  0.0407304   0.04023653  0.04018994  0.04016198  0.03966811  0.04071176
  0.04041358  0.0394072   0.03988243  0.04114041  0.04113109  0.03987312
  0.04024585  0.04069313  0.04099132  0.04049744  0.04010607  0.04049744
  0.03999425  0.04133609  0.04132677  0.04

/Users/Gene/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/Gene/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/Gene/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.

In [9]:
size = 1000
window = 25

# Three dim
# dim1: each datum
# dim2: TimeStep: a sequence of consecutive values 
# dim3: Feature Dimention: There are 7 features
X = np.empty([0, window, len(data)])  
Y = np.zeros(size)
batchSize = 20

print(data.shape)
print(X.shape)
print(data[:, 0:0 + window].shape)
for i in range(size):
    start = randint(0, len(testData)-window-1)
    oneSlice = data[:, start:start + window].T
    # to concatenate, we need to reshape one slice to 3d
    X = np.concatenate((X, np.asarray(oneSlice).reshape(1, window, len(data))), axis = 0) 
    Y[i] = data[2][start + window]    # Need to figure out which is high 
print(X[0])
# X = X.reshape(len(X), len(data)*window)
print(X.shape)
print(Y.shape)

(6, 756)
(0, 25, 6)
(6, 25)
[[ 0.03213891  0.03213891  0.03203212  0.03190065  0.03193702  0.05032806]
 [ 0.03357393  0.03357393  0.03387463  0.03367239  0.03421891  0.02216789]
 [ 0.03461758  0.03461758  0.03472219  0.03474674  0.03433998  0.01819077]
 [ 0.0341703   0.0341703   0.03386542  0.0340682   0.034014    0.01898258]
 [ 0.03397461  0.03397461  0.03456558  0.03420956  0.03477773  0.01971044]
 [ 0.03471076  0.03471076  0.03474061  0.03508601  0.03475911  0.0109676 ]
 [ 0.03458962  0.03458962  0.03427999  0.03449228  0.03409783  0.01450579]
 [ 0.03418894  0.03418894  0.0340681   0.03427553  0.03415371  0.01584453]
 [ 0.0341703   0.0341703   0.03461164  0.03451113  0.03498264  0.02475259]
 [ 0.03486917  0.03486917  0.03472219  0.03515197  0.03492675  0.01529231]
 [ 0.03510213  0.03510213  0.03493408  0.03522737  0.03531793  0.01649083]
 [ 0.03514872  0.03514872  0.03493408  0.0351237   0.03505715  0.01655893]
 [ 0.03526054  0.03526054  0.03529337  0.03548182  0.03568117  0.0207408

In [10]:
# BestParameter so far, mse = 7.5
# model.add(LSTM(80, input_shape=(window, len(data))))
# model.add(Dense(70))
# model.add(Dense(50))
# model.add(Dense(30))
# model.add(Dense(10))
# model.add(Dense(1))

# mse = 6.9
# model.add(Convolution1D(len(data), window*0.5, border_mode='same', input_shape=(window, len(data))))
# model.add(LSTM(int(p*0.8), input_shape=(window, len(data))))
# model.add(Dense(p*0.6))
# model.add(Dense(p*0.3))
# model.add(Dense(p*0.1))
# model.add(Dense(3))
# model.add(Dense(1))

In [11]:
model = Sequential()
p = window*len(data)
print(p)
#model.add(LSTM(1, input_shape=(1000, 25)))
model.add(LSTM(1, input_dim=6,input_length=25))
#model.add(LSTM(1, input_dim=6*25,input_length=1000)
          
# model.add(Convolution1D(64, 3, border_mode='same', input_shape=(10, 32)))
# model.add(Convolution1D(len(data), window*0.2, border_mode='same', input_shape=(window, len(data))))
# model.add(LSTM(int(p*0.4), input_shape=(window, len(data))))
# model.add(Dense(p*0.3))
# model.add(Dense(p*0.1))
# model.add(Dense(3))
# model.add(Dense(1))
model.compile(optimizer='rmsprop',loss='mse') # a mean squared error regression problem
#model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(X, Y, validation_split=0.33, batch_size=batchSize, nb_epoch=20, initial_epoch=0)
print(history)

150
Train on 669 samples, validate on 331 samples
Epoch 1/20
669/669 [==============================] - 5s - loss: 7.3215e-04 - val_loss: 2.5233e-04

In [12]:
model = Sequential()
p = window*len(data)
print(p)
#model.add(LSTM(1, input_shape=(1000, 25)))
model.add(LSTM(1, input_dim=6,input_length=25))
#model.add(dense(1))
#model.add(LSTM(1, input_dim=6*25,input_length=1000)
          
# model.add(Convolution1D(64, 3, border_mode='same', input_shape=(10, 32)))
# model.add(Convolution1D(len(data), window*0.2, border_mode='same', input_shape=(window, len(data))))
# model.add(LSTM(int(p*0.4), input_shape=(window, len(data))))
# model.add(Dense(p*0.3))
# model.add(Dense(p*0.1))
# model.add(Dense(3))
# model.add(Dense(1))
model.compile(optimizer='rmsprop',loss='mse') # a mean squared error regression problem
#model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(X, Y, validation_split=0.33, batch_size=batchSize, nb_epoch=20, initial_epoch=0)
print(history)

150
Train on 669 samples, validate on 331 samples
Epoch 1/20
669/669 [==============================] - 5s - loss: 3.1798e-04 - val_loss: 6.4824e-05